/**
 * Step module: config file writers.
 */

import { dirname, join } from "node:path";
import { writeFileSync } from "node:fs";
import type { AppConfig } from "../types.js";
import type { SecretsConfig } from "../secrets.js";
import { saveAppConfig } from "../storage.js";
import { saveSecrets } from "../secrets.js";
import { success } from "../shared.js";
import type { DockerPaths } from "./types.js";

export async function writeDockerConfigLocalStyle(
  paths: DockerPaths,
  config: AppConfig,
  secrets: SecretsConfig,
): Promise<void> {
  const dockerAppConfigPath = join(paths.configDir, "app.yaml");
  await saveAppConfig(config, dockerAppConfigPath);
  success(`Saved config to: ${dockerAppConfigPath}`);

  const hasSecrets = Object.keys(secrets).length > 0;
  if (!hasSecrets) return;

  await saveSecrets(dockerAppConfigPath, secrets);
  success(`Saved secrets to: ${join(paths.configDir, "secrets.yaml")}`);
}

export async function writeDevConfig(
  config: AppConfig,
  secrets: SecretsConfig,
  appConfigPath: string,
): Promise<void> {
  await saveAppConfig(config, appConfigPath);
  success(`Saved config to: ${appConfigPath}`);

  const hasSecrets = Object.keys(secrets).length > 0;
  if (!hasSecrets) return;

  await saveSecrets(appConfigPath, secrets);
  success(`Saved secrets to: ${dirname(appConfigPath)}/secrets.yaml`);
}

export function buildDockerComposeYaml(
  dockerConfigPath: string,
  tz: string,
  gatewayPort: string,
  defaultImage: string,
): string {
  return `# docker-compose.yml for OwliaBot
# Generated by onboard

services:
  owliabot:
    image: \${OWLIABOT_IMAGE:-${defaultImage}}
    container_name: owliabot
    restart: unless-stopped
    ports:
      - "127.0.0.1:${gatewayPort}:8787"
    volumes:
      - ${dockerConfigPath}:/home/owliabot/.owliabot
      - ${dockerConfigPath}/workspace:/app/workspace
    environment:
      - TZ=${tz}
    command: ["start", "-c", "/home/owliabot/.owliabot/app.yaml"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8787/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
`;
}
